package projectconfig

import (
	"fmt"
	"os"

	"github.com/adrotech/lufy-ai/tools/lufy-cli-go/internal/core/domain"
	"github.com/adrotech/lufy-ai/tools/lufy-cli-go/internal/platform"
	"gopkg.in/yaml.v3"
)

type ConfigStore struct{}

func Load(path string) (ProjectConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return ProjectConfig{}, err
	}
	var node yaml.Node
	if err := yaml.Unmarshal(data, &node); err != nil {
		return ProjectConfig{}, err
	}
	if len(node.Content) == 0 || node.Content[0].Kind != yaml.MappingNode {
		return ProjectConfig{}, fmt.Errorf("formato inválido: se esperaba un mapa YAML")
	}
	var cfg ProjectConfig
	if err := node.Content[0].Decode(&cfg); err != nil {
		return ProjectConfig{}, err
	}
	cfg = applyMissingDefaults(cfg)
	if err := validateHarnessConfig(cfg); err != nil {
		return ProjectConfig{}, err
	}
	if err := validateReviewLimits(cfg.WorkflowLimits.Review); err != nil {
		return ProjectConfig{}, err
	}
	if err := validateAdaptiveRouting(cfg.AdaptiveRouting); err != nil {
		return ProjectConfig{}, err
	}
	return cfg, nil
}

func Marshal(cfg ProjectConfig) ([]byte, error) {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, err
	}
	return append([]byte("# Generated by lufy-ai init. Edit this file to tune project rules.\n"), data...), nil
}

func (s ConfigStore) Exists(path string) (bool, error) {
	_, err := os.Stat(path)
	if err == nil {
		return true, nil
	}
	if os.IsNotExist(err) {
		return false, nil
	}
	return false, err
}

func (s ConfigStore) Load(path string) (ProjectConfig, error) {
	return Load(path)
}

func (s ConfigStore) Write(path string, cfg ProjectConfig) error {
	content, err := Marshal(cfg)
	if err != nil {
		return err
	}
	return platform.WriteFileAtomic(path, content, 0o644)
}

func validateHarnessConfig(cfg ProjectConfig) error {
	return domain.HarnessConfig{
		Tool:              cfg.Tool,
		MethodologyByTier: cfg.MethodologyByTier,
	}.ValidateSupported()
}

func validateReviewLimits(limits WorkflowReviewLimits) error {
	fields := []struct {
		name  string
		value int
	}{
		{name: "max_files_per_slice", value: limits.MaxFilesPerSlice},
		{name: "max_churn_lines_per_slice", value: limits.MaxChurnLinesPerSlice},
		{name: "max_concurrent_slices", value: limits.MaxConcurrentSlices},
		{name: "min_evidence_items", value: limits.MinEvidenceItems},
	}
	for _, field := range fields {
		if field.value < 0 {
			return fmt.Errorf("workflow_limits.review.%s debe ser mayor o igual a cero", field.name)
		}
	}
	return nil
}

func validateAdaptiveRouting(config AdaptiveRoutingConfig) error {
	if config.Mode != "shadow" && config.Mode != "advisory" {
		return fmt.Errorf("adaptive_routing.mode debe ser shadow o advisory")
	}
	if config.PolicyVersion != "deterministic-v1" {
		return fmt.Errorf("adaptive_routing.policy_version debe ser deterministic-v1")
	}
	fields := []struct {
		path  string
		value int
		min   int
		max   int
	}{
		{path: "lease_ttl_seconds", value: config.LeaseTTLSeconds, min: 1, max: 86400},
		{path: "max_candidates", value: config.MaxCandidates, min: 1, max: 32},
		{path: "max_waiting_items", value: config.MaxWaitingItems, min: 1, max: 1024},
		{path: "starvation_after_cycles", value: config.StarvationAfterCycles, min: 1, max: 1000},
	}
	for _, field := range fields {
		if field.value < field.min || field.value > field.max {
			return fmt.Errorf("adaptive_routing.%s debe estar entre %d y %d", field.path, field.min, field.max)
		}
	}
	return nil
}

func applyMissingDefaults(cfg ProjectConfig) ProjectConfig {
	if cfg.ContextGraph.Root == "" && cfg.ContextGraph.Report == "" && len(cfg.ContextGraph.SensitivePatterns) == 0 && len(cfg.ContextGraph.Exclude) == 0 {
		cfg.ContextGraph = DefaultContextGraphConfig()
	}
	if cfg.ContextGraph.Root == "" {
		cfg.ContextGraph.Root = DefaultContextGraphConfig().Root
	}
	if cfg.ContextGraph.Report == "" {
		cfg.ContextGraph.Report = DefaultContextGraphConfig().Report
	}
	if cfg.ContextGraph.MaxQueryResults == 0 {
		cfg.ContextGraph.MaxQueryResults = DefaultContextGraphConfig().MaxQueryResults
	}
	if cfg.ContextGraph.MaxNeighborsPerHint == 0 {
		cfg.ContextGraph.MaxNeighborsPerHint = DefaultContextGraphConfig().MaxNeighborsPerHint
	}
	if len(cfg.ContextGraph.SensitivePatterns) == 0 {
		cfg.ContextGraph.SensitivePatterns = DefaultContextGraphConfig().SensitivePatterns
	}
	if len(cfg.ContextGraph.Exclude) == 0 {
		cfg.ContextGraph.Exclude = DefaultContextGraphConfig().Exclude
	}
	defaults := DefaultRunLedgerConfig()
	if cfg.RunLedger.Enabled == nil {
		cfg.RunLedger.Enabled = defaults.Enabled
	}
	if cfg.RunLedger.Root == "" {
		cfg.RunLedger.Root = defaults.Root
	}
	if cfg.RunLedger.Retention.MaxAgeDays == 0 {
		cfg.RunLedger.Retention.MaxAgeDays = defaults.Retention.MaxAgeDays
	}
	if cfg.RunLedger.Retention.MaxTerminalRuns == 0 {
		cfg.RunLedger.Retention.MaxTerminalRuns = defaults.Retention.MaxTerminalRuns
	}
	if cfg.RunLedger.Retention.MaxBytes == 0 {
		cfg.RunLedger.Retention.MaxBytes = defaults.Retention.MaxBytes
	}
	if cfg.Memory.Vault == "" {
		cfg.Memory.Vault = cfg.Memory.Root
	}
	adaptiveDefaults := DefaultAdaptiveRoutingConfig()
	if cfg.AdaptiveRouting.Mode == "" {
		cfg.AdaptiveRouting.Mode = adaptiveDefaults.Mode
	}
	if cfg.AdaptiveRouting.PolicyVersion == "" {
		cfg.AdaptiveRouting.PolicyVersion = adaptiveDefaults.PolicyVersion
	}
	if cfg.AdaptiveRouting.LeaseTTLSeconds == 0 {
		cfg.AdaptiveRouting.LeaseTTLSeconds = adaptiveDefaults.LeaseTTLSeconds
	}
	if cfg.AdaptiveRouting.MaxCandidates == 0 {
		cfg.AdaptiveRouting.MaxCandidates = adaptiveDefaults.MaxCandidates
	}
	if cfg.AdaptiveRouting.MaxWaitingItems == 0 {
		cfg.AdaptiveRouting.MaxWaitingItems = adaptiveDefaults.MaxWaitingItems
	}
	if cfg.AdaptiveRouting.StarvationAfterCycles == 0 {
		cfg.AdaptiveRouting.StarvationAfterCycles = adaptiveDefaults.StarvationAfterCycles
	}
	return cfg
}
