package projectconfig

import (
	"fmt"
	"os"

	"github.com/adrotech/lufy-ai/tools/lufy-cli-go/internal/core/domain"
	"github.com/adrotech/lufy-ai/tools/lufy-cli-go/internal/platform"
	"gopkg.in/yaml.v3"
)

type ConfigStore struct{}

func Load(path string) (ProjectConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return ProjectConfig{}, err
	}
	var node yaml.Node
	if err := yaml.Unmarshal(data, &node); err != nil {
		return ProjectConfig{}, err
	}
	if len(node.Content) == 0 || node.Content[0].Kind != yaml.MappingNode {
		return ProjectConfig{}, fmt.Errorf("formato inválido: se esperaba un mapa YAML")
	}
	var cfg ProjectConfig
	if err := node.Content[0].Decode(&cfg); err != nil {
		return ProjectConfig{}, err
	}
	cfg = applyMissingDefaults(cfg)
	if err := validateHarnessConfig(cfg); err != nil {
		return ProjectConfig{}, err
	}
	return cfg, nil
}

func Marshal(cfg ProjectConfig) ([]byte, error) {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, err
	}
	return append([]byte("# Generated by lufy-ai init. Edit this file to tune project rules.\n"), data...), nil
}

func (s ConfigStore) Exists(path string) (bool, error) {
	_, err := os.Stat(path)
	if err == nil {
		return true, nil
	}
	if os.IsNotExist(err) {
		return false, nil
	}
	return false, err
}

func (s ConfigStore) Load(path string) (ProjectConfig, error) {
	return Load(path)
}

func (s ConfigStore) Write(path string, cfg ProjectConfig) error {
	content, err := Marshal(cfg)
	if err != nil {
		return err
	}
	return platform.WriteFileAtomic(path, content, 0o644)
}

func validateHarnessConfig(cfg ProjectConfig) error {
	return domain.HarnessConfig{
		Tool:              cfg.Tool,
		MethodologyByTier: cfg.MethodologyByTier,
	}.ValidateSupported()
}

func applyMissingDefaults(cfg ProjectConfig) ProjectConfig {
	if cfg.ContextGraph.Root == "" && cfg.ContextGraph.Report == "" && len(cfg.ContextGraph.SensitivePatterns) == 0 && len(cfg.ContextGraph.Exclude) == 0 {
		cfg.ContextGraph = DefaultContextGraphConfig()
	}
	if cfg.ContextGraph.Root == "" {
		cfg.ContextGraph.Root = DefaultContextGraphConfig().Root
	}
	if cfg.ContextGraph.Report == "" {
		cfg.ContextGraph.Report = DefaultContextGraphConfig().Report
	}
	if cfg.ContextGraph.MaxQueryResults == 0 {
		cfg.ContextGraph.MaxQueryResults = DefaultContextGraphConfig().MaxQueryResults
	}
	if cfg.ContextGraph.MaxNeighborsPerHint == 0 {
		cfg.ContextGraph.MaxNeighborsPerHint = DefaultContextGraphConfig().MaxNeighborsPerHint
	}
	if len(cfg.ContextGraph.SensitivePatterns) == 0 {
		cfg.ContextGraph.SensitivePatterns = DefaultContextGraphConfig().SensitivePatterns
	}
	if len(cfg.ContextGraph.Exclude) == 0 {
		cfg.ContextGraph.Exclude = DefaultContextGraphConfig().Exclude
	}
	if cfg.Memory.Vault == "" {
		cfg.Memory.Vault = cfg.Memory.Root
	}
	return cfg
}
